Cloud v2 Implementation
MiniPlaceholders/MiniPlaceholders pull request #199
Opened 2024-03-27 17:30 UTC by Stampede2011

Migration to Cloud v2, though it seems like they only support Sponge API 7 at this time. May need to stall this PR until then

2024-03-27 17:55 UTC, NickImpact requested changes

2024-03-27 17:55 UTC, NickImpact commented on common/src/main/java/io/github/miniplaceholders/common/PlaceholdersCommand.java
> +                .decorator(component -> Component.text().append(TITLE).appendSpace().append(component).build());
Only thing missed here was registering the exception handler back to the command manager. Should be #registerTo(CommandManager) at the end of the chain there. Might need to play with generics on the create call to let it accept the manager.

2024-07-18 20:15 UTC, 4drian3d reviewed
The only thing missing for me to merge this pull request is to do as requested [here](https://github.com/MiniPlaceholders/MiniPlaceholders/pull/199/files#r1541590672) and maybe prevent cloud from being included in the sponge module until I have Sponge 8 support, but I could do that later

2024-07-24 23:09 UTC, 4drian3d approved these changes

2024-07-24 23:09 UTC, merged